name: grinder
version: 0.6.6+3
author: Devon Carew <devoncarew@google.com>
description: Grinder - a task based, dependency aware build system.
homepage: https://github.com/google/grinder.dart
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  args: '>=0.10.0 <0.13.0'
  cli_util: '>=0.0.1 <0.1.0'
  glob: '>=1.0.0 <2.0.0'
  http_server: '>=0.9.0 <0.10.0'
  unscripted: '>=0.5.2+1 <0.6.0'
  which: '>=0.1.2 <0.2.0'
dev_dependencies:
  browser: any
  unittest: any
executables:
  grind: null
  grinder: null
